# Explore the correctly labelled top 8
We begin by importing packages

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import defaultdict
import matplotlib.pyplot as plt
import datetime 

import sys
import time
import tqdm
from tqdm.auto import tqdm
import pickle
import os

if os.path.exists('/workspace/data'):
    # Load the dictionary of DataFrames from the pickle
    data_path = '/workspace/data/'
else:
    data_path = '../data/'

### Import some data

In [3]:
with open(data_path + 'dfs_dict.pkl', 'rb') as f:
    dfs = pickle.load(f)

tournament_info_df = dfs['tournament_info_df']

In [4]:
players_df = dfs['players_df']
players_df.head()

,game,player_id,tag,all_tags,prefixes,social,country,state,region,c_country,c_state,c_region,placings,characters,alias
0,melee,Rishi,Rishi,[Rishi],[],{'twitter': []},,,,None,None,None,[{'key': 'mdva-invitational-2017-(challonge-mi...,,None
1,melee,15634,lloD,"[lloD, VGz | lloD, Llod]",[],{'twitter': ['lloD74']},United States,VA,,US,CA,Laurel,[{'key': 'mdva-invitational-2017-(challonge-mi...,"{'melee/peach': 1089, 'melee/falco': 1, 'melee...",None
2,melee,6126,Zain,"[Zain, DontTestMe]",[PG],{'twitter': ['PG_Zain']},United States,VA,,US,CA,Los Angeles,[{'key': 'mdva-invitational-2017-(challonge-mi...,"{'melee/marth': 1065, 'melee/pichu': 1, 'melee...",DontTestMe
3,melee,Chu,Chu,[Chu],[],{'twitter': []},,,,None,None,None,[{'key': 'mdva-invitational-2017-(challonge-mi...,,None
4,melee,5620,Junebug,"[Junebug, LS | VGz Junebug]",[],{'twitter': ['arJunebug']},United States,VA,,US,VA,Richmond,[{'key': 'mdva-invitational-2017-(challonge-mi...,"{'melee/sheik': 46, 'melee/falco': 4, 'melee/g...",None

In [ ]:
sets_df = pd.read_pickle(data_path + 'sets_top_8_labeled_df.pkl')
dataset_mini = pd.read_pickle(data_path + 'dataset_mini.pkl')

In [21]:
player = '6126'

mask = (sets_df['p1_id']==player) | (sets_df['p2_id']==player)
sets_df[mask]

,key,game,tournament_key,winner_id,p1_id,p2_id,p1_score,p2_score,location_names,bracket_name,bracket_order,set_order,best_of,game_data,top_8,top_8_location_names,valid_top_8_bracket,top_8_bracket_location_names,major
2,104675845,melee,mdva-invitational-2017-(challonge-mirror),6126,6126,1097,3,0,"[R1, Round 1, Round 1]",,1,C,5,[],False,,False,,False
8,104675851,melee,mdva-invitational-2017-(challonge-mirror),6126,Aglet,6126,1,3,"[R2, Round 2, Round 2]",,1,I,5,[],False,,False,,False
11,104675854,melee,mdva-invitational-2017-(challonge-mirror),Rishi,6126,Rishi,2,3,"[R3, Round 3, Round 3]",,1,L,5,[],False,,False,,False
19,104675862,melee,mdva-invitational-2017-(challonge-mirror),15634,15634,6126,3,2,"[R4, Round 4, Round 4]",,1,T,5,[],False,,False,,False
21,104675864,melee,mdva-invitational-2017-(challonge-mirror),6126,Jerry,6126,0,3,"[R5, Round 5, Round 5]",,1,V,5,[],False,,False,,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1787170,gg__76030970,melee,tipped-off-15-connected-1__melee-singles,6126,6126,15990,3,2,"[WQF, Winners Quarters, Winners Quarter-Final]",Top 32,3,I,3,[],False,,False,,True
1787198,gg__76041921,melee,tipped-off-15-connected-1__melee-singles,1000,6126,1000,0,3,"[WSF, Winners Semis, Winners Semi-Final]",Top 8,4,A,3,[],True,WSF,True,WSF_A,True
1787205,gg__76041937,melee,tipped-off-15-connected-1__melee-singles,1021,6126,1021,0,3,"[LQF, Losers Quarters, Losers Quarter-Final]",Top 8,4,I,3,[],True,LQF,True,LQF_A,True
1787208,gg__75972938,melee,tipped-off-15-connected-1__melee-singles,6126,6126,241093,2,0,"[W1, Winners 1, Winners Round 1]",Phase 2,2,A,3,[],False,,False,,True
1787216,gg__75972946,melee,tipped-off-15-connected-1__melee-singles,6126,6126,4107,3,0,"[WQF, Winners Quarters, Winners Quarter-Final]",Phase 2,2,I,3,[],False,,False,,True

In [6]:
overall_players_rds_new_weekly = pd.read_pickle(data_path + 'overall_players_rds_new_weekly.pkl')
overall_players_ranking_new_weekly = pd.read_pickle(data_path + 'overall_players_ranking_new_weekly.pkl')

In [7]:
char_vs_char_player_rankings_weekly_alt2 = pd.read_pickle(data_path + 'char_vs_char_player_rankings_weekly_alt2.pkl')

In [8]:
sets_df.head(3)

,key,game,tournament_key,winner_id,p1_id,p2_id,p1_score,p2_score,location_names,bracket_name,bracket_order,set_order,best_of,game_data,top_8,top_8_location_names,valid_top_8_bracket,top_8_bracket_location_names,major
0,104675843,melee,mdva-invitational-2017-(challonge-mirror),5620,5620,Chillin,3,1,"[R1, Round 1, Round 1]",,1,A,5,[],False,,False,,False
1,104675844,melee,mdva-invitational-2017-(challonge-mirror),Aglet,15634,Aglet,2,3,"[R1, Round 1, Round 1]",,1,B,5,[],False,,False,,False
2,104675845,melee,mdva-invitational-2017-(challonge-mirror),6126,6126,1097,3,0,"[R1, Round 1, Round 1]",,1,C,5,[],False,,False,,False

In [9]:
dataset_mini.sort_index().head()

,p1_elo,p2_elo,p1_rd,p2_rd,p1_updates,p2_updates,p1_m1_usage,p1_m2_usage,p2_m1_usage,p2_m2_usage,...,p1/m2_elo,p1/m2_rd,p1/m2_updates,p2/m1_elo,p2/m1_rd,p2/m1_updates,p2/m2_elo,p2/m2_rd,p2/m2_updates,winner
0,1995.568005,1500.000000,68.484820,350.000000,10.0,0.0,46.0,4.0,0.0,0.0,...,1500.000000,216.482281,0.0,1500.000000,350.000000,0.0,1500.000000,350.000000,0.0,1.0
1,2094.642998,1500.000000,65.248273,350.000000,10.0,0.0,39.0,1.0,0.0,0.0,...,1408.326897,271.489866,1.0,1500.000000,350.000000,0.0,1500.000000,350.000000,0.0,0.0
2,2105.536004,1960.602597,60.842501,68.984713,13.0,11.0,30.0,0.0,15.0,0.0,...,1500.000000,350.000000,0.0,1533.572543,153.707172,3.0,1500.000000,350.000000,0.0,1.0
3,1500.000000,1910.424390,350.000000,67.612708,0.0,14.0,0.0,0.0,24.0,1.0,...,1500.000000,350.000000,0.0,1602.788856,94.738741,3.0,1279.022079,284.579342,1.0,0.0
4,1500.000000,1500.000000,350.000000,350.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,1500.000000,350.000000,0.0,1500.000000,350.000000,0.0,1500.000000,350.000000,0.0,0.0

In [10]:
dataset_df = pd.merge(sets_df, dataset_mini, left_index=True, right_index=True, how='inner')
print(dataset_df.columns)
dataset_df.head(3)

Index(['key', 'game', 'tournament_key', 'winner_id', 'p1_id', 'p2_id',
       'p1_score', 'p2_score', 'location_names', 'bracket_name',
       'bracket_order', 'set_order', 'best_of', 'game_data', 'top_8',
       'top_8_location_names', 'valid_top_8_bracket',
       'top_8_bracket_location_names', 'major', 'p1_elo', 'p2_elo', 'p1_rd',
       'p2_rd', 'p1_updates', 'p2_updates', 'p1_m1_usage', 'p1_m2_usage',
       'p2_m1_usage', 'p2_m2_usage', 'p1/m1/m1_elo', 'p1/m1/m1_updates',
       'p1/m1/m2_elo', 'p1/m1/m2_updates', 'p1/m2/m1_elo', 'p1/m2/m1_updates',
       'p1/m2/m2_elo', 'p1/m2/m2_updates', 'p2/m1/m1_elo', 'p2/m1/m1_updates',
       'p2/m1/m2_elo', 'p2/m1/m2_updates', 'p2/m2/m1_elo', 'p2/m2/m1_updates',
       'p2/m2/m2_elo', 'p2/m2/m2_updates', 'p1/m1/m1_alt_elo',
       'p1/m1/m1_alt_updates', 'p1/m1/m2_alt_elo', 'p1/m1/m2_alt_updates',
       'p1/m2/m1_alt_elo', 'p1/m2/m1_alt_updates', 'p1/m2/m2_alt_elo',
       'p1/m2/m2_alt_updates', 'p2/m1/m1_alt_elo', 'p2/m1/m1_alt_updates',
       'p2/m1/m2_alt_elo', 'p2/m1/m2_alt_updates', 'p2/m2/m1_alt_elo',
       'p2/m2/m1_alt_updates', 'p2/m2/m2_alt_elo', 'p2/m2/m2_alt_updates',
       'p2/m1/m1_alt_ref_elo', 'p2/m1/m1_alt_ref_updates',
       'p2/m2/m2_alt_ref_elo', 'p2/m2/m2_alt_ref_updates',
       'p1/m1/m1_alt_ref_elo', 'p1/m1/m1_alt_ref_updates',
       'p1/m2/m2_alt_ref_elo', 'p1/m2/m2_alt_ref_updates', 'p1/m1_elo',
       'p1/m1_rd', 'p1/m1_updates', 'p1/m2_elo', 'p1/m2_rd', 'p1/m2_updates',
       'p2/m1_elo', 'p2/m1_rd', 'p2/m1_updates', 'p2/m2_elo', 'p2/m2_rd',
       'p2/m2_updates', 'winner'],
      dtype='object')

,key,game,tournament_key,winner_id,p1_id,p2_id,p1_score,p2_score,location_names,bracket_name,...,p1/m2_elo,p1/m2_rd,p1/m2_updates,p2/m1_elo,p2/m1_rd,p2/m1_updates,p2/m2_elo,p2/m2_rd,p2/m2_updates,winner
0,104675843,melee,mdva-invitational-2017-(challonge-mirror),5620,5620,Chillin,3,1,"[R1, Round 1, Round 1]",,...,1500.000000,216.482281,0.0,1500.000000,350.000000,0.0,1500.0,350.0,0.0,1.0
1,104675844,melee,mdva-invitational-2017-(challonge-mirror),Aglet,15634,Aglet,2,3,"[R1, Round 1, Round 1]",,...,1408.326897,271.489866,1.0,1500.000000,350.000000,0.0,1500.0,350.0,0.0,0.0
2,104675845,melee,mdva-invitational-2017-(challonge-mirror),6126,6126,1097,3,0,"[R1, Round 1, Round 1]",,...,1500.000000,350.000000,0.0,1533.572543,153.707172,3.0,1500.0,350.0,0.0,1.0

In [11]:
overall_players_ranking_new_weekly.head()

,1617201,1497667,2653190,3657740,41449,6039,3621289,3682293,3332271,2034855,...,1911774,4106746,Black hayato,The boy,138692,3293641,1701726,2408932,SmyD,15495
2015-01-01,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,...,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0
2015-01-08,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,...,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0
2015-01-15,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,...,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0
2015-01-22,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,...,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0
2015-01-29,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,...,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0,1500.0

In [12]:
sets_df.head()

,key,game,tournament_key,winner_id,p1_id,p2_id,p1_score,p2_score,location_names,bracket_name,bracket_order,set_order,best_of,game_data,top_8,top_8_location_names,valid_top_8_bracket,top_8_bracket_location_names,major
0,104675843,melee,mdva-invitational-2017-(challonge-mirror),5620,5620,Chillin,3,1,"[R1, Round 1, Round 1]",,1,A,5,[],False,,False,,False
1,104675844,melee,mdva-invitational-2017-(challonge-mirror),Aglet,15634,Aglet,2,3,"[R1, Round 1, Round 1]",,1,B,5,[],False,,False,,False
2,104675845,melee,mdva-invitational-2017-(challonge-mirror),6126,6126,1097,3,0,"[R1, Round 1, Round 1]",,1,C,5,[],False,,False,,False
3,104675846,melee,mdva-invitational-2017-(challonge-mirror),1069,Chu,1069,0,3,"[R1, Round 1, Round 1]",,1,D,5,[],False,,False,,False
4,104675847,melee,mdva-invitational-2017-(challonge-mirror),Rishi,Jerry,Rishi,1,3,"[R1, Round 1, Round 1]",,1,E,5,[],False,,False,,False

In [13]:
tournament_info_df.head(3)

,game,key,cleaned_name,source,tournament_name,tournament_event,season,rank,start,end,country,state,city,entrants,placings,losses,bracket_types,online,lat,lng
0,melee,mdva-invitational-2017-(challonge-mirror),MDVA Invitational 2017 (Challonge Mirror),challonge,https://challonge.com/mdva_invitational_2017,,17,,2017-11-26 08:05:11,2017-11-26 08:48:09,US,VA,Fall's Church,10,"[[Rishi, 1], [15634, 3], [6126, 4], [Chu, 8], ...",{},b'{}',0,NaN,NaN
1,melee,s@sh7,S@SH7,challonge,https://challonge.com/sash7,,17,,2017-06-13 10:27:01,2017-06-13 10:27:01,US,MI,Ann Arbor,92,[],{},b'{}',0,NaN,NaN
2,melee,slippi-champions-league-week-1__melee-singles,Slippi Champions League Week 1,pgstats,slippi-champions-league-week-1,melee-singles,20,,2020-10-11 14:00:00,2020-10-11 14:00:00,,,,20,"[[1000, 1], [6126, 2], [4107, 3], [19554, 3], ...",{},b'{}',1,0.0,0.0

Add the start of a tournament to the set

In [14]:
start_dict = dict(tournament_info_df[['key', 'start']].values)
start_dict

sets_start_df = sets_df.copy()
sets_start_df['start'] = sets_start_df['tournament_key'].map(start_dict)

sets_start_df.head(1)

,key,game,tournament_key,winner_id,p1_id,p2_id,p1_score,p2_score,location_names,bracket_name,bracket_order,set_order,best_of,game_data,top_8,top_8_location_names,valid_top_8_bracket,top_8_bracket_location_names,major,start
0,104675843,melee,mdva-invitational-2017-(challonge-mirror),5620,5620,Chillin,3,1,"[R1, Round 1, Round 1]",,1,A,5,[],False,,False,,False,2017-11-26 08:05:11

Does player 1 win

In [15]:
sets_start_df['p1_win'] = np.equal(sets_start_df['winner_id'], sets_start_df['p1_id'])
sets_start_df.head(1)

,key,game,tournament_key,winner_id,p1_id,p2_id,p1_score,p2_score,location_names,bracket_name,...,set_order,best_of,game_data,top_8,top_8_location_names,valid_top_8_bracket,top_8_bracket_location_names,major,start,p1_win
0,104675843,melee,mdva-invitational-2017-(challonge-mirror),5620,5620,Chillin,3,1,"[R1, Round 1, Round 1]",,...,A,5,[],False,,False,,False,2017-11-26 08:05:11,True

Precompute a sorted order for the character dataframes.

In [19]:
sets_start_df[sets_start_df['top_8']==True].head(30)

,key,game,tournament_key,winner_id,p1_id,p2_id,p1_score,p2_score,location_names,bracket_name,bracket_order,set_order,best_of,game_data,top_8,top_8_location_names,valid_top_8_bracket,top_8_bracket_location_names,major,start
133,90101116,melee,s@sh7,Mew2king (unpaid),Mew2king (unpaid),kjh,1,0,"[WSF, Winners Semis, Winners Semi-Final]",,1,CK,0,[],True,WSF,True,WSF_A,False,2017-06-13 10:27:01
134,90101117,melee,s@sh7,Ginger,1008,Ginger,0,1,"[WSF, Winners Semis, Winners Semi-Final]",,1,CL,0,[],True,WSF,True,WSF_B,False,2017-06-13 10:27:01
135,90101118,melee,s@sh7,Mew2king (unpaid),Mew2king (unpaid),Ginger,1,0,"[WF, Winners Final, Winners Final]",,1,CM,0,[],True,WF,True,WF,False,2017-06-13 10:27:01
220,90101203,melee,s@sh7,tm,Bbbbbbbbbexic,tm,0,1,"[L8, Losers 8, Losers Round 8]",,1,FV,0,[],True,LN,True,LN_B,False,2017-06-13 10:27:01
221,90101204,melee,s@sh7,lain,lain,math,1,0,"[L8, Losers 8, Losers Round 8]",,1,FW,0,[],True,LN,True,LN_A,False,2017-06-13 10:27:01
222,90101205,melee,s@sh7,1008,1008,tm,1,0,"[LQF, Losers Quarters, Losers Quarter-Final]",,1,FX,0,[],True,LQF,True,LQF_B,False,2017-06-13 10:27:01
223,90101206,melee,s@sh7,kjh,kjh,lain,1,0,"[LQF, Losers Quarters, Losers Quarter-Final]",,1,FY,0,[],True,LQF,True,LQF_A,False,2017-06-13 10:27:01
224,90101207,melee,s@sh7,kjh,1008,kjh,0,1,"[LSF, Losers Semis, Losers Semi-Final]",,1,FZ,0,[],True,LSF,True,LSF,False,2017-06-13 10:27:01
225,90101208,melee,s@sh7,kjh,Ginger,kjh,0,1,"[LF, Losers Final, Losers Final]",,1,GA,0,[],True,LF,True,LF,False,2017-06-13 10:27:01
226,90101209,melee,s@sh7,Mew2king (unpaid),Mew2king (unpaid),kjh,1,0,"[GF, Grand Final, Grand Final]",,1,CN,0,[],True,GF,True,GF,False,2017-06-13 10:27:01
489,,melee,httpsparagonchallongecomla_2015_melee_singles,1000,1000,16342,3,1,"[WSF, Winners Semis, Winners Semi-Final]",,1,BI,5,[],True,WSF,True,WSF_A,True,2015-09-06 23:45:46
490,,melee,httpsparagonchallongecomla_2015_melee_singles,1003,4465,1003,1,3,"[WSF, Winners Semis, Winners Semi-Final]",,1,BJ,5,[],True,WSF,True,WSF_B,True,2015-09-06 23:45:46
491,,melee,httpsparagonchallongecomla_2015_melee_singles,1000,1000,1003,3,1,"[WF, Winners Final, Winners Final]",,1,BK,5,[],True,WF,True,WF,True,2015-09-06 23:45:46
548,,melee,httpsparagonchallongecomla_2015_melee_singles,1008,1023,1008,0,3,"[L7, Losers 7, Losers Round 7]",,1,DR,5,[],True,LN,True,LN_A,True,2015-09-06 23:45:46
549,,melee,httpsparagonchallongecomla_2015_melee_singles,1004,1004,13932,3,1,"[L7, Losers 7, Losers Round 7]",,1,DS,5,[],True,LN,True,LN_B,True,2015-09-06 23:45:46
550,,melee,httpsparagonchallongecomla_2015_melee_singles,1008,16342,1008,1,3,"[LQF, Losers Quarters, Losers Quarter-Final]",,1,DT,5,[],True,LQF,True,LQF_A,True,2015-09-06 23:45:46
551,,melee,httpsparagonchallongecomla_2015_melee_singles,1004,4465,1004,1,3,"[LQF, Losers Quarters, Losers Quarter-Final]",,1,DU,5,[],True,LQF,True,LQF_B,True,2015-09-06 23:45:46
552,,melee,httpsparagonchallongecomla_2015_melee_singles,1004,1008,1004,0,3,"[LSF, Losers Semis, Losers Semi-Final]",,1,DV,5,[],True,LSF,True,LSF,True,2015-09-06 23:45:46
553,,melee,httpsparagonchallongecomla_2015_melee_singles,1003,1003,1004,3,2,"[LF, Losers Final, Losers Final]",,1,DW,5,[],True,LF,True,LF,True,2015-09-06 23:45:46
554,,melee,httpsparagonchallongecomla_2015_melee_singles,1000,1000,1003,3,2,"[GF, Grand Final, Grand Final]",,1,BL,5,[],True,GF,True,GF,True,2015-09-06 23:45:46
615,,melee,httpsdl4-5challongecomdl45meleeprobracket,6189,6189,6103,3,0,"[WSF, Winners Semis, Winners Semi-Final]",,1,BI,5,[],True,WSF,True,WSF_A,False,2015-05-02 23:55:20
616,,melee,httpsdl4-5challongecomdl45meleeprobracket,4465,4465,12870,3,0,"[WSF, Winners Semis, Winners Semi-Final]",,1,BJ,5,[],True,WSF,True,WSF_B,False,2015-05-02 23:55:20
617,,melee,httpsdl4-5challongecomdl45meleeprobracket,6189,6189,4465,3,1,"[WF, Winners Final, Winners Final]",,1,BK,5,[],True,WF,True,WF,False,2015-05-02 23:55:20
674,,melee,httpsdl4-5challongecomdl45meleeprobracket,Hack,Hack,Vdogg,3,0,"[L7, Losers 7, Losers Round 7]",,1,DR,5,[],True,LN,True,LN_A,False,2015-05-02 23:55:20
675,,melee,httpsdl4-5challongecomdl45meleeprobracket,Thomas,4215,Thomas,1,3,"[L7, Losers 7, Losers Round 7]",,1,DS,5,[],True,LN,True,LN_B,False,2015-05-02 23:55:20
676,,melee,httpsdl4-5challongecomdl45meleeprobracket,6103,6103,Hack,3,2,"[LQF, Losers Quarters, Losers Quarter-Final]",,1,DT,5,[],True,LQF,True,LQF_A,False,2015-05-02 23:55:20
677,,melee,httpsdl4-5challongecomdl45meleeprobracket,12870,12870,Thomas,3,0,"[LQF, Losers Quarters, Losers Quarter-Final]",,1,DU,5,[],True,LQF,True,LQF_B,False,2015-05-02 23:55:20
678,,melee,httpsdl4-5challongecomdl45meleeprobracket,6103,6103,12870,3,2,"[LSF, Losers Semis, Losers Semi-Final]",,1,DV,5,[],True,LSF,True,LSF,False,2015-05-02 23:55:20
679,,melee,httpsdl4-5challongecomdl45meleeprobracket,4465,4465,6103,3,0,"[LF, Losers Final, Losers Final]",,1,DW,5,[],True,LF,True,LF,False,2015-05-02 23:55:20
680,,melee,httpsdl4-5challongecomdl45meleeprobracket,6189,6189,4465,3,0,"[GF, Grand Final, Grand Final]",,1,BL,5,[],True,GF,True,GF,False,2015-05-02 23:55:20

In [16]:
columns = char_vs_char_player_rankings_weekly_alt2.columns

# the columns of the dataframe are not in order
char_rating_cols_np = np.sort(np.array(columns))
char_rating_cols_argsort = np.argsort(np.array(columns))
char_rating_player_ids = np.array([col.split('/')[0] for col in char_rating_cols_np])[::729]

print(char_rating_player_ids[:10])
print(char_rating_cols_np[:10])
print(char_vs_char_player_rankings_weekly_alt2.columns[char_rating_cols_argsort[:10]])

['1000' '10060' '1010559' '1017' '1022796' '1030' '1035454' '1043677'
 '1050586' '10538']
['1000/captainfalcon/captainfalcon' '1000/captainfalcon/falco'
 '1000/captainfalcon/fox' '1000/captainfalcon/iceclimbers'
 '1000/captainfalcon/marth' '1000/captainfalcon/peach'
 '1000/captainfalcon/sheik' '1000/drmario/jigglypuff' '1000/drmario/peach'
 '1000/falco/captainfalcon']
Index(['1000/captainfalcon/captainfalcon', '1000/captainfalcon/falco',
       '1000/captainfalcon/fox', '1000/captainfalcon/iceclimbers',
       '1000/captainfalcon/marth', '1000/captainfalcon/peach',
       '1000/captainfalcon/sheik', '1000/drmario/jigglypuff',
       '1000/drmario/peach', '1000/falco/captainfalcon'],
      dtype='object')

In [18]:
char_rating_cols_argsort

array([ 61764,  61765,  61766, ..., 185292, 185293, 185294])

In [ ]:
from tqdm import tqdm
tqdm.pandas()  # Enable progress_apply with tqdm

# Define the function to retrieve ratings and ratings deviation values
def get_values(start_date, p1_id, p2_id, ratings_df, rd_df, char_ratings_df, char_rating_player_ids, char_rating_cols_argsort):
    values = []
    try:
        row = ratings_df.index[np.searchsorted(ratings_df.index, start_date)]
        values.append(ratings_df.loc[row, p1_id])
        values.append(ratings_df.loc[row, p1_id])
        values.append(rd_df.loc[row, p1_id])
        values.append(rd_df.loc[row, p2_id])
        # values.append(char_ratings_df.loc[row, [p1_id + '/' + key for key in char_char]])
        p1_start = np.searchsorted(player_ids, p1_id) * 729
        values.append(rd_df.iloc[row, cols_argsort[p1_start:p1_start+729]])
        p2_start = np.searchsorted(player_ids, p2_id)
        values.append(rd_df.iloc[row, cols_argsort[p2_start:p2_start+729]])
        
    except:
        return [np.nan, np.nan, np.nan, np.nan]  # Ensure four NaNs are returned if an error occurs


start_dict = dict(tournament_info_df[['key', 'start']].values)
start_dict

sets_start_df = sets_df.copy()
sets_start_df['start'] = sets_start_df['tournament_key'].map(start_dict)

sets_start_df.head(1)

# the columns of the dataframe are not in order
cols_np = np.sort(np.array(char_vs_char_player_rankings_weekly_alt2.columns))
cols_argsort = np.argsort(np.array(char_vs_char_player_rankings_weekly_alt2.columns))
player_ids = np.array([col.split('/')[0] for col in cols_np])[:: 729]

# Apply the function with progress tracking and expand the list into columns
result_df = sets_start_df.progress_apply(
    lambda row: get_values(row['start'], row['p1_id'], row['p2_id'], overall_players_ranking_new_weekly, overall_players_rds_new_weekly, char_vs_char_player_rankings_weekly_alt2, player_ids, cols_argsort), 
    axis=1,
    result_type='expand'  # This option expands the returned list into separate columns
)



# Assign result to new columns in the original DataFrame
# sets_start_df[['p1_rating', 'p2_rating', 'p1_rd', 'p2_rd']] = result_df

100%|██████████| 1795681/1795681 [01:36<00:00, 18652.18it/s]

In [ ]:
player_id = players_df['player_id']
characters = list(dict([[col.split('/')[1], 1] for col in columns]).keys())
char_char = [char_1 + '/' + char_2 for char_1 in characters for char_2 in characters]
char_char

['sheik/sheik',
 'sheik/falco',
 'sheik/jigglypuff',
 'sheik/donkeykong',
 'sheik/fox',
 'sheik/kirby',
 'sheik/link',
 'sheik/marth',
 'sheik/peach',
 'sheik/random',
 'sheik/captainfalcon',
 'sheik/roy',
 'sheik/drmario',
 'sheik/luigi',
 'sheik/mario',
 'sheik/pikachu',
 'sheik/samus',
 'sheik/yoshi',
 'sheik/iceclimbers',
 'sheik/zelda',
 'sheik/bowser',
 'sheik/younglink',
 'sheik/mewtwo',
 'sheik/ganondorf',
 'sheik/mrgameandwatch',
 'sheik/ness',
 'sheik/pichu',
 'falco/sheik',
 'falco/falco',
 'falco/jigglypuff',
 'falco/donkeykong',
 'falco/fox',
 'falco/kirby',
 'falco/link',
 'falco/marth',
 'falco/peach',
 'falco/random',
 'falco/captainfalcon',
 'falco/roy',
 'falco/drmario',
 'falco/luigi',
 'falco/mario',
 'falco/pikachu',
 'falco/samus',
 'falco/yoshi',
 'falco/iceclimbers',
 'falco/zelda',
 'falco/bowser',
 'falco/younglink',
 'falco/mewtwo',
 'falco/ganondorf',
 'falco/mrgameandwatch',
 'falco/ness',
 'falco/pichu',
 'jigglypuff/sheik',
 'jigglypuff/falco',
 'jigglypuff/jigglypuff',
 'jigglypuff/donkeykong',
 'jigglypuff/fox',
 'jigglypuff/kirby',
 'jigglypuff/link',
 'jigglypuff/marth',
 'jigglypuff/peach',
 'jigglypuff/random',
 'jigglypuff/captainfalcon',
 'jigglypuff/roy',
 'jigglypuff/drmario',
 'jigglypuff/luigi',
 'jigglypuff/mario',
 'jigglypuff/pikachu',
 'jigglypuff/samus',
 'jigglypuff/yoshi',
 'jigglypuff/iceclimbers',
 'jigglypuff/zelda',
 'jigglypuff/bowser',
 'jigglypuff/younglink',
 'jigglypuff/mewtwo',
 'jigglypuff/ganondorf',
 'jigglypuff/mrgameandwatch',
 'jigglypuff/ness',
 'jigglypuff/pichu',
 'donkeykong/sheik',
 'donkeykong/falco',
 'donkeykong/jigglypuff',
 'donkeykong/donkeykong',
 'donkeykong/fox',
 'donkeykong/kirby',
 'donkeykong/link',
 'donkeykong/marth',
 'donkeykong/peach',
 'donkeykong/random',
 'donkeykong/captainfalcon',
 'donkeykong/roy',
 'donkeykong/drmario',
 'donkeykong/luigi',
 'donkeykong/mario',
 'donkeykong/pikachu',
 'donkeykong/samus',
 'donkeykong/yoshi',
 'donkeykong/iceclimbers',
 'donkeykong/zelda',
 'donkeykong/bowser',
 'donkeykong/younglink',
 'donkeykong/mewtwo',
 'donkeykong/ganondorf',
 'donkeykong/mrgameandwatch',
 'donkeykong/ness',
 'donkeykong/pichu',
 'fox/sheik',
 'fox/falco',
 'fox/jigglypuff',
 'fox/donkeykong',
 'fox/fox',
 'fox/kirby',
 'fox/link',
 'fox/marth',
 'fox/peach',
 'fox/random',
 'fox/captainfalcon',
 'fox/roy',
 'fox/drmario',
 'fox/luigi',
 'fox/mario',
 'fox/pikachu',
 'fox/samus',
 'fox/yoshi',
 'fox/iceclimbers',
 'fox/zelda',
 'fox/bowser',
 'fox/younglink',
 'fox/mewtwo',
 'fox/ganondorf',
 'fox/mrgameandwatch',
 'fox/ness',
 'fox/pichu',
 'kirby/sheik',
 'kirby/falco',
 'kirby/jigglypuff',
 'kirby/donkeykong',
 'kirby/fox',
 'kirby/kirby',
 'kirby/link',
 'kirby/marth',
 'kirby/peach',
 'kirby/random',
 'kirby/captainfalcon',
 'kirby/roy',
 'kirby/drmario',
 'kirby/luigi',
 'kirby/mario',
 'kirby/pikachu',
 'kirby/samus',
 'kirby/yoshi',
 'kirby/iceclimbers',
 'kirby/zelda',
 'kirby/bowser',
 'kirby/younglink',
 'kirby/mewtwo',
 'kirby/ganondorf',
 'kirby/mrgameandwatch',
 'kirby/ness',
 'kirby/pichu',
 'link/sheik',
 'link/falco',
 'link/jigglypuff',
 'link/donkeykong',
 'link/fox',
 'link/kirby',
 'link/link',
 'link/marth',
 'link/peach',
 'link/random',
 'link/captainfalcon',
 'link/roy',
 'link/drmario',
 'link/luigi',
 'link/mario',
 'link/pikachu',
 'link/samus',
 'link/yoshi',
 'link/iceclimbers',
 'link/zelda',
 'link/bowser',
 'link/younglink',
 'link/mewtwo',
 'link/ganondorf',
 'link/mrgameandwatch',
 'link/ness',
 'link/pichu',
 'marth/sheik',
 'marth/falco',
 'marth/jigglypuff',
 'marth/donkeykong',
 'marth/fox',
 'marth/kirby',
 'marth/link',
 'marth/marth',
 'marth/peach',
 'marth/random',
 'marth/captainfalcon',
 'marth/roy',
 'marth/drmario',
 'marth/luigi',
 'marth/mario',
 'marth/pikachu',
 'marth/samus',
 'marth/yoshi',
 'marth/iceclimbers',
 'marth/zelda',
 'marth/bowser',
 'marth/younglink',
 'marth/mewtwo',
 'marth/ganondorf',
 'marth/mrgameandwatch',
 'marth/ness',
 'marth/pichu',
 'peach/sheik',
 'peach/falco',
 'peach/jigglypuff',
 'peach/donkeykong',
 'peach/fox',
 'peach/kirby',
 'peach/link',
 'peach/marth',
 'peach/peach',
 'peach/random',
 'peach/captainfalcon',
 'peach/roy',
 'peach/drmario',
 'peach/luigi',
 'peach/mario',
 'peach/pikachu',
 'peach/samus',
 'peach/yoshi',
 'peach/iceclimbers',
 'peach/zelda',
 'peach/bowser',
 'peach/younglink',
 'peach/mewtwo',
 'peach/ganondorf',
 'peach/mrgameandwatch',
 'peach/ness',
 'peach/pichu',
 'random/sheik',
 'random/falco',
 'random/jigglypuff',
 'random/donkeykong',
 'random/fox',
 'random/kirby',
 'random/link',
 'random/marth',
 'random/peach',
 'random/random',
 'random/captainfalcon',
 'random/roy',
 'random/drmario',
 'random/luigi',
 'random/mario',
 'random/pikachu',
 'random/samus',
 'random/yoshi',
 'random/iceclimbers',
 'random/zelda',
 'random/bowser',
 'random/younglink',
 'random/mewtwo',
 'random/ganondorf',
 'random/mrgameandwatch',
 'random/ness',
 'random/pichu',
 'captainfalcon/sheik',
 'captainfalcon/falco',
 'captainfalcon/jigglypuff',
 'captainfalcon/donkeykong',
 'captainfalcon/fox',
 'captainfalcon/kirby',
 'captainfalcon/link',
 'captainfalcon/marth',
 'captainfalcon/peach',
 'captainfalcon/random',
 'captainfalcon/captainfalcon',
 'captainfalcon/roy',
 'captainfalcon/drmario',
 'captainfalcon/luigi',
 'captainfalcon/mario',
 'captainfalcon/pikachu',
 'captainfalcon/samus',
 'captainfalcon/yoshi',
 'captainfalcon/iceclimbers',
 'captainfalcon/zelda',
 'captainfalcon/bowser',
 'captainfalcon/younglink',
 'captainfalcon/mewtwo',
 'captainfalcon/ganondorf',
 'captainfalcon/mrgameandwatch',
 'captainfalcon/ness',
 'captainfalcon/pichu',
 'roy/sheik',
 'roy/falco',
 'roy/jigglypuff',
 'roy/donkeykong',
 'roy/fox',
 'roy/kirby',
 'roy/link',
 'roy/marth',
 'roy/peach',
 'roy/random',
 'roy/captainfalcon',
 'roy/roy',
 'roy/drmario',
 'roy/luigi',
 'roy/mario',
 'roy/pikachu',
 'roy/samus',
 'roy/yoshi',
 'roy/iceclimbers',
 'roy/zelda',
 'roy/bowser',
 'roy/younglink',
 'roy/mewtwo',
 'roy/ganondorf',
 'roy/mrgameandwatch',
 'roy/ness',
 'roy/pichu',
 'drmario/sheik',
 'drmario/falco',
 'drmario/jigglypuff',
 'drmario/donkeykong',
 'drmario/fox',
 'drmario/kirby',
 'drmario/link',
 'drmario/marth',
 'drmario/peach',
 'drmario/random',
 'drmario/captainfalcon',
 'drmario/roy',
 'drmario/drmario',
 'drmario/luigi',
 'drmario/mario',
 'drmario/pikachu',
 'drmario/samus',
 'drmario/yoshi',
 'drmario/iceclimbers',
 'drmario/zelda',
 'drmario/bowser',
 'drmario/younglink',
 'drmario/mewtwo',
 'drmario/ganondorf',
 'drmario/mrgameandwatch',
 'drmario/ness',
 'drmario/pichu',
 'luigi/sheik',
 'luigi/falco',
 'luigi/jigglypuff',
 'luigi/donkeykong',
 'luigi/fox',
 'luigi/kirby',
 'luigi/link',
 'luigi/marth',
 'luigi/peach',
 'luigi/random',
 'luigi/captainfalcon',
 'luigi/roy',
 'luigi/drmario',
 'luigi/luigi',
 'luigi/mario',
 'luigi/pikachu',
 'luigi/samus',
 'luigi/yoshi',
 'luigi/iceclimbers',
 'luigi/zelda',
 'luigi/bowser',
 'luigi/younglink',
 'luigi/mewtwo',
 'luigi/ganondorf',
 'luigi/mrgameandwatch',
 'luigi/ness',
 'luigi/pichu',
 'mario/sheik',
 'mario/falco',
 'mario/jigglypuff',
 'mario/donkeykong',
 'mario/fox',
 'mario/kirby',
 'mario/link',
 'mario/marth',
 'mario/peach',
 'mario/random',
 'mario/captainfalcon',
 'mario/roy',
 'mario/drmario',
 'mario/luigi',
 'mario/mario',
 'mario/pikachu',
 'mario/samus',
 'mario/yoshi',
 'mario/iceclimbers',
 'mario/zelda',
 'mario/bowser',
 'mario/younglink',
 'mario/mewtwo',
 'mario/ganondorf',
 'mario/mrgameandwatch',
 'mario/ness',
 'mario/pichu',
 'pikachu/sheik',
 'pikachu/falco',
 'pikachu/jigglypuff',
 'pikachu/donkeykong',
 'pikachu/fox',
 'pikachu/kirby',
 'pikachu/link',
 'pikachu/marth',
 'pikachu/peach',
 'pikachu/random',
 'pikachu/captainfalcon',
 'pikachu/roy',
 'pikachu/drmario',
 'pikachu/luigi',
 'pikachu/mario',
 'pikachu/pikachu',
 'pikachu/samus',
 'pikachu/yoshi',
 'pikachu/iceclimbers',
 'pikachu/zelda',
 'pikachu/bowser',
 'pikachu/younglink',
 'pikachu/mewtwo',
 'pikachu/ganondorf',
 'pikachu/mrgameandwatch',
 'pikachu/ness',
 'pikachu/pichu',
 'samus/sheik',
 'samus/falco',
 'samus/jigglypuff',
 'samus/donkeykong',
 'samus/fox',
 'samus/kirby',
 'samus/link',
 'samus/marth',
 'samus/peach',
 'samus/random',
 'samus/captainfalcon',
 'samus/roy',
 'samus/drmario',
 'samus/luigi',
 'samus/mario',
 'samus/pikachu',
 'samus/samus',
 'samus/yoshi',
 'samus/iceclimbers',
 'samus/zelda',
 'samus/bowser',
 'samus/younglink',
 'samus/mewtwo',
 'samus/ganondorf',
 'samus/mrgameandwatch',
 'samus/ness',
 'samus/pichu',
 'yoshi/sheik',
 'yoshi/falco',
 'yoshi/jigglypuff',
 'yoshi/donkeykong',
 'yoshi/fox',
 'yoshi/kirby',
 'yoshi/link',
 'yoshi/marth',
 'yoshi/peach',
 'yoshi/random',
 'yoshi/captainfalcon',
 'yoshi/roy',
 'yoshi/drmario',
 'yoshi/luigi',
 'yoshi/mario',
 'yoshi/pikachu',
 'yoshi/samus',
 'yoshi/yoshi',
 'yoshi/iceclimbers',
 'yoshi/zelda',
 'yoshi/bowser',
 'yoshi/younglink',
 'yoshi/mewtwo',
 'yoshi/ganondorf',
 'yoshi/mrgameandwatch',
 'yoshi/ness',
 'yoshi/pichu',
 'iceclimbers/sheik',
 'iceclimbers/falco',
 'iceclimbers/jigglypuff',
 'iceclimbers/donkeykong',
 'iceclimbers/fox',
 'iceclimbers/kirby',
 'iceclimbers/link',
 'iceclimbers/marth',
 'iceclimbers/peach',
 'iceclimbers/random',
 'iceclimbers/captainfalcon',
 'iceclimbers/roy',
 'iceclimbers/drmario',
 'iceclimbers/luigi',
 'iceclimbers/mario',
 'iceclimbers/pikachu',
 'iceclimbers/samus',
 'iceclimbers/yoshi',
 'iceclimbers/iceclimbers',
 'iceclimbers/zelda',
 'iceclimbers/bowser',
 'iceclimbers/younglink',
 'iceclimbers/mewtwo',
 'iceclimbers/ganondorf',
 'iceclimbers/mrgameandwatch',
 'iceclimbers/ness',
 'iceclimbers/pichu',
 'zelda/sheik',
 'zelda/falco',
 'zelda/jigglypuff',
 'zelda/donkeykong',
 'zelda/fox',
 'zelda/kirby',
 'zelda/link',
 'zelda/marth',
 'zelda/peach',
 'zelda/random',
 'zelda/captainfalcon',
 'zelda/roy',
 'zelda/drmario',
 'zelda/luigi',
 'zelda/mario',
 'zelda/pikachu',
 'zelda/samus',
 'zelda/yoshi',
 'zelda/iceclimbers',
 'zelda/zelda',
 'zelda/bowser',
 'zelda/younglink',
 'zelda/mewtwo',
 'zelda/ganondorf',
 'zelda/mrgameandwatch',
 'zelda/ness',
 'zelda/pichu',
 'bowser/sheik',
 'bowser/falco',
 'bowser/jigglypuff',
 'bowser/donkeykong',
 'bowser/fox',
 'bowser/kirby',
 'bowser/link',
 'bowser/marth',
 'bowser/peach',
 'bowser/random',
 'bowser/captainfalcon',
 'bowser/roy',
 'bowser/drmario',
 'bowser/luigi',
 'bowser/mario',
 'bowser/pikachu',
 'bowser/samus',
 'bowser/yoshi',
 'bowser/iceclimbers',
 'bowser/zelda',
 'bowser/bowser',
 'bowser/younglink',
 'bowser/mewtwo',
 'bowser/ganondorf',
 'bowser/mrgameandwatch',
 'bowser/ness',
 'bowser/pichu',
 'younglink/sheik',
 'younglink/falco',
 'younglink/jigglypuff',
 'younglink/donkeykong',
 'younglink/fox',
 'younglink/kirby',
 'younglink/link',
 'younglink/marth',
 'younglink/peach',
 'younglink/random',
 'younglink/captainfalcon',
 'younglink/roy',
 'younglink/drmario',
 'younglink/luigi',
 'younglink/mario',
 'younglink/pikachu',
 'younglink/samus',
 'younglink/yoshi',
 'younglink/iceclimbers',
 'younglink/zelda',
 'younglink/bowser',
 'younglink/younglink',
 'younglink/mewtwo',
 'younglink/ganondorf',
 'younglink/mrgameandwatch',
 'younglink/ness',
 'younglink/pichu',
 'mewtwo/sheik',
 'mewtwo/falco',
 'mewtwo/jigglypuff',
 'mewtwo/donkeykong',
 'mewtwo/fox',
 'mewtwo/kirby',
 'mewtwo/link',
 'mewtwo/marth',
 'mewtwo/peach',
 'mewtwo/random',
 'mewtwo/captainfalcon',
 'mewtwo/roy',
 'mewtwo/drmario',
 'mewtwo/luigi',
 'mewtwo/mario',
 'mewtwo/pikachu',
 'mewtwo/samus',
 'mewtwo/yoshi',
 'mewtwo/iceclimbers',
 'mewtwo/zelda',
 'mewtwo/bowser',
 'mewtwo/younglink',
 'mewtwo/mewtwo',
 'mewtwo/ganondorf',
 'mewtwo/mrgameandwatch',
 'mewtwo/ness',
 'mewtwo/pichu',
 'ganondorf/sheik',
 'ganondorf/falco',
 'ganondorf/jigglypuff',
 'ganondorf/donkeykong',
 'ganondorf/fox',
 'ganondorf/kirby',
 'ganondorf/link',
 'ganondorf/marth',
 'ganondorf/peach',
 'ganondorf/random',
 'ganondorf/captainfalcon',
 'ganondorf/roy',
 'ganondorf/drmario',
 'ganondorf/luigi',
 'ganondorf/mario',
 'ganondorf/pikachu',
 'ganondorf/samus',
 'ganondorf/yoshi',
 'ganondorf/iceclimbers',
 'ganondorf/zelda',
 'ganondorf/bowser',
 'ganondorf/younglink',
 'ganondorf/mewtwo',
 'ganondorf/ganondorf',
 'ganondorf/mrgameandwatch',
 'ganondorf/ness',
 'ganondorf/pichu',
 'mrgameandwatch/sheik',
 'mrgameandwatch/falco',
 'mrgameandwatch/jigglypuff',
 'mrgameandwatch/donkeykong',
 'mrgameandwatch/fox',
 'mrgameandwatch/kirby',
 'mrgameandwatch/link',
 'mrgameandwatch/marth',
 'mrgameandwatch/peach',
 'mrgameandwatch/random',
 'mrgameandwatch/captainfalcon',
 'mrgameandwatch/roy',
 'mrgameandwatch/drmario',
 'mrgameandwatch/luigi',
 'mrgameandwatch/mario',
 'mrgameandwatch/pikachu',
 'mrgameandwatch/samus',
 'mrgameandwatch/yoshi',
 'mrgameandwatch/iceclimbers',
 'mrgameandwatch/zelda',
 'mrgameandwatch/bowser',
 'mrgameandwatch/younglink',
 'mrgameandwatch/mewtwo',
 'mrgameandwatch/ganondorf',
 'mrgameandwatch/mrgameandwatch',
 'mrgameandwatch/ness',
 'mrgameandwatch/pichu',
 'ness/sheik',
 'ness/falco',
 'ness/jigglypuff',
 'ness/donkeykong',
 'ness/fox',
 'ness/kirby',
 'ness/link',
 'ness/marth',
 'ness/peach',
 'ness/random',
 'ness/captainfalcon',
 'ness/roy',
 'ness/drmario',
 'ness/luigi',
 'ness/mario',
 'ness/pikachu',
 'ness/samus',
 'ness/yoshi',
 'ness/iceclimbers',
 'ness/zelda',
 'ness/bowser',
 'ness/younglink',
 'ness/mewtwo',
 'ness/ganondorf',
 'ness/mrgameandwatch',
 'ness/ness',
 'ness/pichu',
 'pichu/sheik',
 'pichu/falco',
 'pichu/jigglypuff',
 'pichu/donkeykong',
 'pichu/fox',
 'pichu/kirby',
 'pichu/link',
 'pichu/marth',
 'pichu/peach',
 'pichu/random',
 'pichu/captainfalcon',
 'pichu/roy',
 'pichu/drmario',
 'pichu/luigi',
 'pichu/mario',
 'pichu/pikachu',
 'pichu/samus',
 'pichu/yoshi',
 'pichu/iceclimbers',
 'pichu/zelda',
 'pichu/bowser',
 'pichu/younglink',
 'pichu/mewtwo',
 'pichu/ganondorf',
 'pichu/mrgameandwatch',
 'pichu/ness',
 'pichu/pichu']